AUTH0_SECRET='use [openssl rand -hex 32] to generate a 32 bytes value'
AUTH0_BASE_URL='http://localhost:3000'
AUTH0_ISSUER_BASE_URL='https://dev-vq8kks87.us.auth0.com'
AUTH0_CLIENT_ID='cD7LFRxgQCsIii1ahYQVBU45mbFCpXC9'
AUTH0_CLIENT_SECRET='mlOSMCXDZLGFC_CWz7sZAbnpQpSyO1fnH1fc4CPhKqTvYT7Ehe1sezwZaItd53qa'
